name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Permissions
        run: chmod +x srdk

      - name: Build mrpack
        run: ./srdk build

      - name: Build offline mrpack
        run: ./srdk build_offline

      - uses: actions/upload-artifact@v7
        with:
          name: modpack
          path: build/*.mrpack