name: Release

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Permissions
        run: chmod +x srdk

      - name: Read version
        id: version
        run: |
          ver=$(jq -r '.Version' shulker/proj.json)
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Build mrpack
        run: ./srdk build

      - name: Build offline mrpack
        run: ./srdk build_offline

      - uses: softprops/action-gh-release@v3
        with:
          name: ${{ steps.version.outputs.version }}
          files: build/*.mrpack
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
